### PR TITLE
update switch

### PR DESCRIPTION
**Pull request by cqhtyi**

### CODE REVIEW

**Comment by MuJJus** [comment]
VPN should not be excluded at the same time, we need it to carry other protocols like UDP.

**Comment by MuJJus** [comment]
VPN should not be excluded at the same time, we need it to carry other protocols like UDP.

**Comment by cqhtyi** [comment]
But in international mode, the proxy server uses the VPN tunnel.
How to deal with it?

**Comment by MuJJus** [comment]
Maybe we can design a exclude feature.

**Pull request closed without merging**
